language: node_js
node_js:
- 9
sudo: required
services:
- docker
script:
- npx parcel build index.html
- docker build -t vatusa/frontend .
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag vatusa/frontend vatusa/frontend:latest;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push vatusa/frontend;
  fi
- if [ "$TRAVIS_BRANCH" == "devel" ]; then
    docker tag vatusa/frontend vatusa/frontend:devel;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push vatusa/frontend:devel;
  fi
