language: node_js
node_js:
- 9
sudo: required
services:
- docker
before_install:
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
script:
- npm install
- npx poi build
- docker-compose build
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag vatusa/frontend vatusa/frontend:latest;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push vatusa/frontend;
  fi
- if [ "$TRAVIS_BRANCH" == "devel" ]; then
    docker tag vatusa/frontend vatusa/frontend:devel
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push vatusa/frontend:devel;
  fi
