language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run test
  - npm run build

deploy:
  skip_cleanup: true
  provider: script
  script: "/bin/sh deploy.sh"
  on:
  branch: master
